### ISSUE TITLE
类型不支持当前js版本

### ISSUE THREAD

**Issue by krislee94** [huanxsd/react-native-refresh-list-view#1]
在运行的时候，有些定义，例如：onHeaderRefresh：func 等处，该如何解决。

**Comment by huanxsd** [comment]
简单粗暴的方式是把这个代码去掉。
    propTypes: {
        onHeaderRefresh: func,
        onFooterRefresh: func,
    }

或者改成：
    static propTypes = {
        onHeaderRefresh: React.PropTypes.func,
        onFooterRefresh: React.PropTypes.func,
    }
