### ISSUE TITLE
请问支持Android吗？

### ISSUE THREAD

**Issue by charleylla** [huanxsd/react-native-refresh-list-view#10]
如题

**Comment by huanxsd** [comment]
支持

**Comment by charleylla** [comment]
在安卓平台下，滑到底部不会触发 onTouchEnd 事件，而是需要下拉一点再进行滑动才可以触发，请问有解决方案吗？你可以测试下这个问题

**Comment by huanxsd** [comment]
试一下将onEndReachedThreshold设置为0.1~0.5左右，

```
onEndReachedThreshold?: ?number 
```
> 决定当距离内容最底部还有多远时触发onEndReached回调。注意此参数是一个比值而非像素单位。比如，0.5表示距离内容最底部的距离为当前列表可见长度的一半时触发。
