### ISSUE TITLE
第一次请求数据的时候，也会执行上拉刷新！

### ISSUE THREAD

**Issue by meiqi1992** [huanxsd/react-native-refresh-list-view#11]
第一次请求数据的时候，也会执行上拉刷新，也就是第一次加载的时候 上拉和下拉都会执行？怎么破？

**Comment by zhaoqianpeng123** [comment]
同问，我也遇到

**Comment by huanxsd** [comment]
出现这个问题的版本号是多少，试下最新版（1.0.5），有修复过这个问题

**Comment by huanxsd** [comment]
第一次请求数据的时候，也会执行上拉刷新，也就是第一次加载的时候 上拉和下拉都会执行

**Comment by youngxiaoran** [comment]
请求数据后会执行上拉回调，数据少的时候
