### ISSUE TITLE
页面数据不足以渲染整个屏幕时，会触发加载更多

### ISSUE THREAD

**Issue by wuhenzhizao** [huanxsd/react-native-refresh-list-view#15]
页面数据不足时，会自动触发加载更多，用demo试了一下也有这种情况 @huanxsd #

**Comment by huanxsd** [comment]
目前设计是这样，除非设成NoMoreData。不然如果不满一页，是会自动触发加载更多的

**Comment by meiqi1992** [comment]
有解决办法嘛？还是FlatList就是会这样，第一次加载数据出来的时候，都会触发加载更多？

**Comment by meiqi1992** [comment]
@wuhenzhizao 有解决嘛？

**Comment by hrh94** [comment]
![tim 20180309163306](https://user-images.githubusercontent.com/16442574/37198160-567bc6ec-23b8-11e8-97e8-98a064e3ee29.png)

**Comment by huanxsd** [comment]
楼上正解
