### ISSUE TITLE
底部刷新会一次调用两遍

### ISSUE THREAD

**Issue by LHJ-K2S** [huanxsd/react-native-refresh-list-view#19]
每次上拉都会调用两次。
    我用FlatList的onEndReached方法也会出现这个问题。
    我现在是设定了一个timer让0.2秒之内无法再次上拉加载。 但又有新的问题：如果用户使劲上拉，0.2秒内就上拉了两次会导致永远无法触发onFooterRefresh方法，直到重新下拉刷新过一次。（FlatList也有这个问题）。
    不知道是啥原因，有没有大神说下思路？

**Comment by LHJ-K2S** [comment]
demo并没有这个多次调用的问题。。。我继续研究研究。。

**Comment by LHJ-K2S** [comment]
原来需要包个父View并且设置flex=1

**Comment by waterfly** [comment]
我这边也是每次都走两次，请问你那边知道是为什么了么？

**Comment by huanxsd** [comment]
触发下拉刷新回调后，需要及时将状态置为RefreshState.HeaderRefreshing。
