### ISSUE TITLE
Cannot read property 'endRefreshing' of undefined

### ISSUE THREAD

**Issue by 520xiaopohai** [huanxsd/react-native-refresh-list-view#2]
Warning: Can only update a mounted or mounting component. This usually means you called setState, replaceState, or forceUpdate on an unmounted component. This is a no-op.

Please check the code for the ProductListScene component.
Cannot read property 'endRefreshing' of undefined

**Comment by huanxsd** [comment]
现在可以不用ref了，直接修改列表组件的props
<RefreshListView
  ....
  refreshState={this.state.refreshState}
/>
// 下拉刷新
this.setState({refreshState: RefreshState.HeaderRefreshing})

// 上拉翻页
this.setState({refreshState: RefreshState.FooterRefreshing})

// 加载成功
this.setState({refreshState: RefreshState.Idle})

// 加载失败
this.setState({refreshState: RefreshState.Failure})

// 加载全部数据
this.setState({refreshState: RefreshState.NoMoreData})
