### ISSUE TITLE
 服务器错误或者返回数据为空

### ISSUE THREAD

**Issue by 13980519619** [huanxsd/react-native-refresh-list-view#20]
看了你代码，错误和数据为空是在footer里面写的。
我觉得错误时，应该在页面中间提示比如：’服务器错误‘
或者没数据时，在页面中间提示’暂无数据‘

我想的是，是用两种方法：
1，是用ListEmptyComponent 2.是用一个状态，错误的时候显示提示组建，有数据是显示flatlist，我想问问你项目中怎么处理的呢

**Comment by huanxsd** [comment]
这个看你们具体业务需求
我是直接显示在footer里

**Comment by qiandingqin** [comment]
数据为空的时候 状态应该为：RefreshState.EmptyData

**Comment by huanxsd** [comment]
在1.0.10版本中，增加footerNoMoreDataComponent属性，可以自定义空数据状态

**Comment by xiechuanyu** [comment]
没有数据和网络错误不是同一种状态
