### ISSUE TITLE
上拉刷新的问题

### ISSUE THREAD

**Issue by liuyuan1993** [huanxsd/react-native-refresh-list-view#21]
Android平台发现第一次进入界面的时候底部的提示语为什么要出来，然后点击提示语会走上啦刷新的回调，之后再上拉的时候不会重新走回调了，这是怎么回事

**Comment by huanxsd** [comment]
正常第一次进页面，需要把列表设置成刷新中的状态，例如：
this.setState({ refreshState: RefreshState.HeaderRefreshing })

**Comment by huanxsd** [comment]
在1.0.9版本中修复这个问题
