### ISSUE TITLE
下拉刷新，数据没有满屏，会自动触发上拉加载

### ISSUE THREAD

**Issue by m131-8** [huanxsd/react-native-refresh-list-view#28]
下拉刷新，数据没有满屏，会自动触发上拉加载

**Comment by cyixlq** [comment]
这个应该是FlatList上的问题，也不能叫问题，特性吧。如果最底部那个列表项的几分之一可见就会触发加载更多

**Comment by xgAnd** [comment]
老哥们现在这个问题是怎么解决的呢 我现在也是遇到的就是一进入页面就自动执行了两次上拉加载更多。

**Comment by cyixlq** [comment]
我认为要不就是适当增高列表项高度，要不就是找懂原生的写控件，要不就是一开始就显示两页，但是不漏声色

**Comment by xgAnd** [comment]
现在只有几条数据就自动去触发了加载更多传了加1的页码就没有数据了 空了  只有一两条数据不能就占满屏幕了吧太丑了。

**Comment by huanxsd** [comment]
目前设计是这样，不满一屏就会再次触发上拉刷新。
建议一次多取几条数据。如果一次请求不满一屏，体验也不是太好
