### ISSUE TITLE
scrollToIndex is not a function

### ISSUE THREAD

**Issue by bitting304** [huanxsd/react-native-refresh-list-view#29]
![a7cf35a6-eb4e-4c9f-9d72-4d911cc240b1](https://user-images.githubusercontent.com/19605962/41810825-2508e572-7737-11e8-86bf-08092a482bf9.png)
没有办法使用scrollToIndex 代码如下：
 return <View style={styles.container}>
            <RefreshListView
                ref={list=>this.list=list}
                data={this.state.dataArray}
                keyExtractor={this.keyExtractor}
                renderItem={(data)=>this._renderItem(data)}
                refreshState={this.state.refreshState}
                onHeaderRefresh={this.onHeaderRefresh}
                onFooterRefresh={this.onFooterRefresh}
                ListHeaderComponent={this.renderHeader()}
                // 可选
                footerRefreshingText= '玩命加载中 >.<'
                footerFailureText = '居然失败了,点击重试 =.=!'
                footerNoMoreDataText= '-我是有底线的-'
                footerEmptyDataText= '-好像什么东西都没有了-'
            />
            {this.renderBottomView()}
        </View>

  <TouchableOpacity
                    activeOpacity={1}
                    onPress={()=>{
                        this.list.scrollToIndex({viewPosition: 0, index: 3});
                    }}
                >
                    <Image
                        source={require('../../img/comment.png')}
                        style={{width:32,height:32,alignSelf:'stretch',}}
                    />
                    {commNum}
                </TouchableOpacity>

**Comment by huanxsd** [comment]
因为RefreshListView不是直接继承FlatList，而是在外部包装了一层组件。
如果要获取到FlatList实例，需要在外部设置listRef

**Comment by huanxsd** [comment]
listRef={list=>this.list=list}
