### ISSUE TITLE
界面没显示数据

### ISSUE THREAD

**Issue by damiaozi** [huanxsd/react-native-refresh-list-view#4]
RefreshListView componentWillReceiveProps {"data":[],"refreshState":0}
RefreshListView componentDidUpdate {"data":[],"refreshState":0}     state: null

RefreshListView componentWillReceiveProps {"data":[有数据有内容],"refreshState":0}

RefreshListView componentDidUpdate {"data":[],"refreshState":0}     state: null

界面没显示数据

**Comment by huanxsd** [comment]
帮忙贴下具体实现的代码
