### ISSUE TITLE
ref怎么操作？

### ISSUE THREAD

**Issue by chensong526025** [huanxsd/react-native-refresh-list-view#47]
你好，用你的这个组件，如何传递ref，例如想代码控制列表滑动到顶部，ref怎么绑定？

**Comment by huanxsd** [comment]
可以设置listRef属性

**Comment by chensong526025** [comment]
谢谢



------------------ 原始邮件 ------------------
发件人: "Daniel"<notifications@github.com>; 
发送时间: 2019年7月30日(星期二) 上午10:46
收件人: "huanxsd/react-native-refresh-list-view"<react-native-refresh-list-view@noreply.github.com>; 
抄送: "风"<447220278@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [huanxsd/react-native-refresh-list-view] ref怎么操作？ (#47)




可以设置listRef属性
