### ISSUE TITLE
默认会加载 更多

### ISSUE THREAD

**Issue by combing520** [huanxsd/react-native-refresh-list-view#8]
按照 给的 例子来做， 默认会调用 【加载更多】， 从而导致，我本来想加载第一页的数据，然后竟然将我所有的数据都加载出来了， 请问 需要怎样控制，按照的就是 你 Example 下面的 src下面的那个Demo.js

**Comment by suiyi1420** [comment]
我大致看了下楼主封装的代码，没有运行过，Demo.js在定义列表的时候少了个属性：onEndReachedThreshold，该属性是决定当距离内容最底部还有多远时触发onEndReached回调。注意此参数是一个比值而非像素单位。比如，0.5表示距离内容最底部的距离为当前列表可见长度的一半时触发。

**Comment by huanxsd** [comment]
onEndReachedThreshold设置成0，也是会触发onEndReached的。

@combing520 这个控件目前都会默认调用【加载更多】。
如果你想用户手动点击翻页，不能在onEndReached中调用请求接口。
需要另外在列表底部添加按钮。用户点击后，触发刷新。

**Comment by suiyi1420** [comment]
没记错的话 onEndReached这个方法只会调用一次，要实现上拉加载更多，我是通过在onscroll里判断当前滑动的长度是否大于等于列表的总长度，然后触发请求

**Comment by huanxsd** [comment]
已修复，详见 #9
