### ISSUE TITLE
_onFooterRefresh会不停触发

### ISSUE THREAD

**Issue by FanChael** [huanxsd/react-native-refresh-list-view#9]
我用pageNumber去分页请求，一加载完成就会触发_onFooterRefresh，导致不停加载，最后加载完了。请教大神。

**Comment by huanxsd** [comment]
你一次请求多少条数据，onEndReachedThreshold设置成0试一下

**Comment by FanChael** [comment]
1. 我试试。 我请求几条数据都是一样的，一加载完就会触发上拉事件，然后再加载数据，又触发上拉事件。2. 一开始用的就是FlatList，然后试了下onEndReached事件，本来以为只有到达底部才会触发这个事件，但是一开始在constructor里面请求两三条数据进行初始化后就会触发这个事件。3. 我的是Android平台。 我不知道是哪里配置问题还是怎么回事。   onEndReachedThreshold设置成0，_onFooterRefresh不会执行？

**Comment by FanChael** [comment]
再补充下，我照着您的Demo模拟了_onHeaderRefresh = () => {
        this.setState({refreshState: RefreshState.HeaderRefreshing})

        // 模拟网络请求
        setTimeout(() => {
            // 模拟网络加载失败的情况
            // if (Math.random() < 0.2) {
            //     this.setState({refreshState: RefreshState.Failure})
            //     return
            // }
            //获取测试数据
            let dataList = this.getTestList();
            // Alert.alert('aaaa:' + dataList.length);
            this.setState({
                recItems: dataList,
                refreshState: RefreshState.Idle,
            })
        }, 2000)
    }
在componentDidMount里面调用了一下这个方法初始化第一个页面；
然后： 
refreshState={this.state.refreshState}
                    onHeaderRefresh={this._onHeaderRefresh}
                    onFooterRefresh={/*this._onFooterRefresh*/()=>{
                        Alert.alert('test');
                    }}
我发现只要下拉刷新或者首次调用，都会弹窗，也就是都会跟随一个onFooterRefresh事件。好头疼呀，哥。

**Comment by FanChael** [comment]
这就是导致不用下拉刷新就自动刷刷加载完所有数据的原因。哈哈。

**Comment by huanxsd** [comment]
确实有这个问题，已修复，onEndReachedThreshold默认设置0.1

**Comment by FanChael** [comment]
好的。谢谢。为什么原生插件也有这个问题，我看原生文档没有提到说设置这个0.1，是不是我没注意？ 发自网易邮箱大师 在2017年10月28日 18:41，Daniel 写道： 确实有这个问题，已修复，onEndReachedThreshold默认设置0.1 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by LyCharlie** [comment]
onEndReachedThreshold设置成0.1有效 但是为什么？
